documentos/urls.py
# documentos/urls.py

from django.urls import path
from . import views

app_name = 'documentos'

urlpatterns = [
    path('categorias/', views.listar_categorias, name='listar_categorias'),
    path('categorias/criar/', views.criar_categoria, name='criar_categoria'),
    path('categorias/editar/<int:pk>/', views.editar_categoria, name='editar_categoria'),
    path('categorias/excluir/<int:pk>/', views.excluir_categoria, name='excluir_categoria'),

    # Rotas de documentos
    path('listar_documentos/', views.listar_documentos_aprovados, name='listar_documentos_aprovados'),
    path('aprovar_pendentes/', views.listar_aprovacoes_pendentes, name='listar_aprovacoes_pendentes'),
    path('documentos/criar/', views.criar_documento, name='criar_documento'),
    path('visualizar/<int:id>/', views.visualizar_documento, name='visualizar_documento'),
    path('aprovar/<int:documento_id>/', views.aprovar_documento, name='aprovar_documento'),
    path('reprovar/<int:documento_id>/', views.reprovar_documento, name='reprovar_documento'),
    path('nova-revisao/<int:documento_id>/', views.nova_revisao, name='nova_revisao'),
    path('visualizar_acessos/<int:id>/', views.visualizar_acessos_documento, name='visualizar_acessos_documento'),
    path('documentos/reprovados/', views.listar_documentos_reprovados, name='listar_documentos_reprovados'),
    # outras rotas...

]

gestao_documentos/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import views as usuarios_views  # Importa as views do app 'usuarios'
from gestao_documentos import views as gestao_documentos_views  # Importa as views do app 'gestao_documentos'
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from gestao_documentos.views import home  # Importa a view home corrigida

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Inclui as URLs do app 'usuarios'
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('perfil/', usuarios_views.ProfileView.as_view(), name='perfil_usuario'),
    path('documentos/', include('documentos.urls', namespace='documentos')),  # URLs relacionadas a documentos
    path('notificacoes/', include('notificacoes.urls')),  # URLs relacionadas a notificações
     
    
]

# Para servir arquivos de mídia durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import ProfileView
from . import views  



app_name = 'usuarios'

urlpatterns = [
    path('registrar/', views.registrar_usuario, name='registrar'),
    path('login/', views.login_usuario, name='login_usuario'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('editar/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('buscar_usuarios/', views.buscar_usuarios_ad, name='buscar_usuarios_ad'),
    path('importar_usuarios/', views.importar_usuarios_ad, name='importar_usuarios_ad'),
    path('grupos/', views.lista_grupos, name='lista_grupos'),
    path('grupos/cadastrar_grupo/', views.cadastrar_grupo, name='cadastrar_grupo'),
    path('grupos/buscar_participantes/', views.buscar_participantes, name='buscar_participantes'),
    path('grupos/editar_grupo/<int:grupo_id>/', views.editar_grupo, name='editar_grupo'),
    path('grupos/excluir_grupo/<int:grupo_id>/', views.excluir_grupo, name='excluir_grupo'),
    path('liberar_permissoes/', views.liberar_permissoes, name='liberar_permissoes'),
    path('sugestoes/', views.sugestoes, name='sugestoes'),
    path('perfil/', ProfileView.as_view(), name='perfil_usuario'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),

]

gestao_documentos/views.py
# views.py

from django.shortcuts import render
import requests
import time
import logging

logger = logging.getLogger(__name__)

# Variáveis para armazenar o cache e o tempo da última atualização
previsao_cache = None
ultima_atualizacao = 0

# Função para mapear a condição ao ícone
def selecionar_icone(condicao):
    condicao_map = {
        'sol com algumas nuvens': '2',
        'sol com muitas nuvens': '2r',
        'sol': '1',
        'noite sem nuvens': '1n',
        'noite com algumas nuvens': '2n',
        'noite com muitas nuvens': '2rn',
        'nublado': '3',
        'sol e chuva': '4',
        'sol com muitas nuvens e chuva': '4r',
        'noite chuvosa': '4n',
        'noite nublada e chuvosa': '4rn',
        'sol entre nuvens e pancadas de chuva, com trovoadas': '4t',
        'pancadas de chuva durante a noite': '4tn',
        'chuvoso': '5',
        'chuva e trovoadas': '6',
        'geada': '7',
        'neve': '8',
        'nevoeiro': '9',
        'pancadas de chuva': '4',
        'muitas nuvens': '3'


    }

    condicao_normalizada = condicao.lower()

    for chave, icone in condicao_map.items():
        if chave in condicao_normalizada:
            return icone

    return 'default'

# Função para obter o clima atual
def obter_clima_atual(cidade_id, api_key):
    url_atual = f"https://apiadvisor.climatempo.com.br/api/v1/weather/locale/{cidade_id}/current?token={api_key}"
    try:
        resposta = requests.get(url_atual)
        resposta.raise_for_status()
        dados = resposta.json()
        condicao_clima = dados['data']['condition']
        print(f"Condição climática recebida: {condicao_clima}")  # Adicione esta linha
        clima_atual = {
            'temperatura_atual': dados['data']['temperature'],
            'sensacao': dados['data']['sensation'],
            'humidade': dados['data']['humidity'],
            'condicao': condicao_clima,
            'icone': selecionar_icone(condicao_clima),
            'data': dados['data']['date']
        }
        logger.debug(f"Clima atual obtido: {clima_atual}")
        return clima_atual
    except Exception as e:
        logger.error(f"Erro ao obter clima atual: {e}")
        return None

# Função para obter a previsão de 15 dias com cache
def obter_previsao_15_dias(cidade_id, api_key, intervalo_cache=3600):
    global previsao_cache, ultima_atualizacao

    if time.time() - ultima_atualizacao > intervalo_cache or previsao_cache is None:
        url_previsao = f"https://apiadvisor.climatempo.com.br/api/v1/forecast/locale/{cidade_id}/days/15?token={api_key}"
        try:
            resposta = requests.get(url_previsao)
            resposta.raise_for_status()
            dados = resposta.json()
            previsao = []
            for dia in dados.get('data', []):
                condicao_clima = dia['text_icon']['text']['phrase']['reduced']
                previsao.append({
                    'data': dia['date'],
                    'data_br': dia['date_br'],
                    'temperatura_min': dia['temperature']['min'],
                    'temperatura_max': dia['temperature']['max'],
                    'condicao': condicao_clima,
                    'condicao_icone': selecionar_icone(condicao_clima),
                    'probabilidade_chuva': dia['rain']['probability'],
                })
            previsao_cache = previsao
            ultima_atualizacao = time.time()
            logger.debug("Previsão atualizada e armazenada em cache.")
        except Exception as e:
            logger.error(f"Erro ao obter previsão: {e}")
            return None

    return previsao_cache

# View da home
def home(request):
    cidade_id = 5585  # Carazinho, RS
    api_key = '5f713c18b31aee4d7a93df6a3220cfb8'  # Substitua pela sua chave de API

    # Obter clima atual e previsão com cache
    clima_atual = obter_clima_atual(cidade_id, api_key)
    previsao = obter_previsao_15_dias(cidade_id, api_key)

    dia_atual = int(request.GET.get('dia', 0))  # Controle dos dias na previsão

    # Impedir dias negativos
    if dia_atual < 0:
        dia_atual = 0

    erro = ''
    if clima_atual and previsao:
        if dia_atual < len(previsao):
            previsao_atual = previsao[dia_atual]
        else:
            previsao_atual = previsao[0]
            dia_atual = 0
    else:
        previsao_atual = None
        erro = 'Erro ao obter dados do tempo.'

    context = {
        'clima_atual': clima_atual,
        'previsao': previsao_atual,
        'dia_atual': dia_atual,
        'erro': erro,
    }

    logger.debug(f"Contexto enviado para o template: {context}")

    return render(request, 'home.html', context)

gestao_documentos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Portal Rotoplastyc{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <!-- Menu Superior -->
    <header class="top-bar">
        <div class="menu-icon" onclick="toggleMenu()">
            <span class="icon">&#9776;</span>
        </div>

        <!-- Notificações e Perfil agrupados -->
        <div class="top-bar-right">
            <!-- Notificações -->
            <div class="notification-bell">
                <a href="#" onclick="toggleNotificationDropdown()" class="notification-link">
                    <img src="{% static 'images/notificacao.png' %}" alt="Notificações" class="bell-icon">
                    {% if notificacoes_nao_lidas|length > 0 %}
                        <span class="notification-count" id="notification-count">{{ notificacoes_nao_lidas|length }}</span>
                    {% endif %}
                </a>
                <div id="notification-dropdown" class="notification-dropdown">
                    <ul id="notification-list">
                        {% for notificacao in notificacoes_nao_lidas %}
                            <li id="notification-{{ notificacao.id }}">
                                <div class="notification-message">
                                    <!-- Exibindo a foto do solicitante -->
                                    <img src="{% if notificacao.solicitante.profile_photo and notificacao.solicitante.profile_photo.url != '' %}{{ notificacao.solicitante.profile_photo.url }}{% else %}{% static 'images/default_user.png' %}{% endif %}" alt="Foto do Solicitante" class="user-avatar">
                                    <p>{{ notificacao.mensagem }}</p>
                                    <div class="notification-controls">
                                        <a href="{% url 'documentos:listar_aprovacoes_pendentes' %}" class="notification-action">Ir para aprovações</a>
                                    </div>
                                </div>
                                <button class="close-notification" data-id="{{ notificacao.id }}">✖</button>
                            </li>
                        {% empty %}
                            <li>Nenhuma notificação pendente.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- Menu de perfil -->
            <div class="profile-dropdown">
                <div class="profile-icon" onclick="toggleProfileMenu()">
                    <img src="{% if user.profile_photo and user.profile_photo.url != '' %}{{ user.profile_photo.url }}{% else %}{% static 'images/default_user.png' %}{% endif %}" alt="Usuário" class="profile-photo">
                    <span class="dropdown">&#9660;</span>
                </div>
                <div id="profile-menu" class="profile-menu">
                    <div class="profile-info">
                        <p>Minha Conta ({{ user.username }})</p>
                        <p>{{ user.email }}</p>
                    </div>
                    <ul>
                        <li><a href="{% url 'usuarios:perfil_usuario' %}">Perfil do Usuário</a></li>
                        <li><a href="{% url 'logout' %}">Sair</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <!-- Menu Lateral -->
    <nav class="side-bar" id="side-bar">
        <ul>
            <li>
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/home-icon.png' %}" alt="Home">
                    <span class="menu-label">Home</span>
                </a>
            </li>
            <li>
                <a href="#" onclick="toggleSubmenu(event, this)">
                    <img src="{% static 'images/documento.png' %}" alt="Documentos">
                    <span class="menu-label">Documentos</span>
                </a>
                <ul class="submenu">
                    <li><a href="{% url 'documentos:listar_documentos_aprovados' %}">Listar Documentos</a></li>
                    <li><a href="{% url 'documentos:listar_aprovacoes_pendentes' %}">Aprovações Pendentes</a></li>
                    <li><a href="{% url 'documentos:listar_documentos_reprovados' %}">Reprovações</a></li>
                    <li><a href="{% url 'documentos:listar_categorias' %}">Categorias</a></li>
                </ul>
            </li>
            <li>
                <a href="#" onclick="toggleSubmenu(event, this)">
                    <img src="{% static 'images/administracao.png' %}" alt="Administração">
                    <span class="menu-label">Administração</span>
                </a>
                <ul class="submenu">
                    <li><a href="{% url 'usuarios:lista_usuarios' %}">Usuários</a></li>
                    <li><a href="{% url 'usuarios:lista_grupos' %}">Grupos de Usuários</a></li>
                    <li><a href="{% url 'usuarios:liberar_permissoes' %}">Permissões</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    <!-- Conteúdo da página -->
    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Scripts globais -->
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

        function toggleMenu() {
            var sideBar = document.getElementById("side-bar");
            sideBar.classList.toggle("expanded");

            if (!sideBar.classList.contains("expanded")) {
                var submenus = document.querySelectorAll('.submenu');
                submenus.forEach(function(submenu) {
                    submenu.classList.remove('open');
                });
            }
        }

        function toggleNotificationDropdown() {
            var notificationDropdown = document.getElementById("notification-dropdown");
            notificationDropdown.classList.toggle("open");
        }

        function toggleProfileMenu() {
            var profileMenu = document.getElementById("profile-menu");
            profileMenu.classList.toggle("open");
        }

        function toggleSubmenu(event, element) {
            event.preventDefault();

            if (document.getElementById("side-bar").classList.contains("expanded")) {
                var submenu = element.nextElementSibling;
                submenu.classList.toggle('open');
                var allSubmenus = document.querySelectorAll('.submenu');
                allSubmenus.forEach(function(s) {
                    if (s !== submenu) {
                        s.classList.remove('open');
                    }
                });
            }
        }

        document.addEventListener('click', function(event) {
            var profileMenu = document.getElementById("profile-menu");
            var notificationDropdown = document.getElementById("notification-dropdown");

            if (!profileMenu.contains(event.target) && !event.target.closest('.profile-icon')) {
                profileMenu.classList.remove('open');
            }

            if (!notificationDropdown.contains(event.target) && !event.target.closest('.notification-bell')) {
                notificationDropdown.classList.remove('open');
            }
        });

        // Atualiza o contador de notificações na bolinha
        function updateNotificationCount() {
            const notificationCountElement = document.getElementById('notification-count');
            let currentCount = parseInt(notificationCountElement.textContent);
            currentCount = currentCount - 1;
            if (currentCount > 0) {
                notificationCountElement.textContent = currentCount;
            } else {
                notificationCountElement.style.display = 'none';
            }
        }

        // Enviar a requisição para marcar a notificação como lida
        document.querySelectorAll('.close-notification').forEach(function(button) {
            button.addEventListener('click', function() {
                var notificacaoId = this.getAttribute('data-id');
                console.log('Clicado para fechar notificação com ID:', notificacaoId);

                fetch(`/notificacoes/marcar-notificacao-como-lida/${notificacaoId}/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': csrftoken,
                        'Content-Type': 'application/json',
                    }
                })
                .then(response => {
                    if (response.ok) {
                        console.log('Notificação marcada como lida.');
                        this.closest('li').style.display = 'none';
                        updateNotificationCount();  // Atualizar o contador
                    } else {
                        console.error('Erro ao marcar a notificação como lida.');
                    }
                })
                .catch(error => console.error('Erro:', error));
            });
        });
    </script>

    {% block extra_js %}{% endblock %}
</body>
</html>

gestao_documentos/templates/home.html
<!-- home.html -->

{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="weather-card">
    {% if erro %}
        <p>{{ erro }}</p>
    {% else %}
        <!-- Clima Atual -->
        {% if clima_atual %}
            <div class="current-weather-container">
                <h2>Clima Atual</h2>
                <p>{{ clima_atual.data }}</p>
                {% if clima_atual.icone %}
                    <img src="{% static 'images/' %}{{ clima_atual.icone }}.png" alt="Ícone do tempo" class="weather-icon">
                {% endif %}
                <h1>{{ clima_atual.temperatura_atual }}°C</h1>
                <p>Sensação: {{ clima_atual.sensacao }}°C</p>
                <p>Humidade: {{ clima_atual.humidade }}%</p>
                <p>{{ clima_atual.condicao }}</p>
            </div>
        {% else %}
            <p>Dados do clima atual não disponíveis.</p>
        {% endif %}

        <!-- Linha de separação -->
        <div class="separator-line"></div>

        <!-- Previsão -->
        {% if previsao %}
            <div class="forecast-container">
                <h2>Previsão do Dia</h2>
                <div class="forecast-content">
                    <button class="prev-day" onclick="mudarDia({{ dia_atual|add:'-1' }})">&#8249;</button>
                    <div id="previsao-dia">
                        <p>{{ previsao.data_br }}</p>
                        {% if previsao.condicao_icone %}
                            <img src="{% static 'images/' %}{{ previsao.condicao_icone }}.png" alt="Ícone do tempo" class="weather-icon">
                        {% else %}
                            <p>Sem ícone para a condição: {{ previsao.condicao }}</p>
                        {% endif %}
                        <div class="temp-container">
                            <h1>{{ previsao.temperatura_max }}°C</h1>
                            <p>Min: {{ previsao.temperatura_min }}°C Max: {{ previsao.temperatura_max }}°C</p>
                        </div>
                        <p>
                            <img src="{% static 'images/rain-icon.png' %}" alt="Chuva" class="rain-icon">
                            {{ previsao.probabilidade_chuva }}%
                        </p>
                        <p>{{ previsao.condicao }}</p>
                    </div>
                    <button class="next-day" onclick="mudarDia({{ dia_atual|add:'1' }})">&#8250;</button>
                </div>
            </div>
        {% else %}
            <p>Dados de previsão não disponíveis.</p>
        {% endif %}
    {% endif %}
</div>

<script>
    function mudarDia(dia) {
        const queryString = new URLSearchParams(window.location.search);
        queryString.set('dia', dia);
        window.location.search = queryString.toString();
    }
</script>
{% endblock %}

gestao_documentos/templates/previsao.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="weather-card">
    <!-- Previsão -->
    <div class="forecast-container">
        <h2>Previsão do dia</h2>
        <div class="forecast-content">
            <button class="prev-day" onclick="mudarDia({{ dia_atual|add:'-1' }})">&#8249;</button>
            <div id="previsao-dia">
                <div class="temp-container">
                    {% if previsao.condicao_icone %}
                        <img src="{% static 'images/' %}{{ previsao.condicao_icone }}.png" alt="Ícone do tempo" class="weather-icon">
                    {% endif %}
                    <h1>{{ previsao.temperatura_max }}°C</h1>
                </div>
                <p>Min: {{ previsao.temperatura_min }}°C Max: {{ previsao.temperatura_max }}°C</p>
                <div class="temp-container">
                    <img src="{% static 'images/rain-icon.png' %}" alt="Chuva" class="rain-icon">
                    <p>{{ previsao.probabilidade_chuva }}%</p>
                </div>
                <p>{{ previsao.condicao }}</p>
            </div>
            <button class="next-day" onclick="mudarDia({{ dia_atual|add:'1' }})">&#8250;</button>
        </div>
    </div>
</div>

<script>
    function mudarDia(dia) {
        const queryString = new URLSearchParams(window.location.search);
        queryString.set('dia', dia);
        window.location.search = queryString.toString();
    }
</script>
{% endblock %}

gestao_documentos/templates/previsao_15_dias.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Previsão de 15 Dias</title>
</head>
<body>
    <h1>Previsão de 15 dias</h1>
    {% if previsao %}
    <table>
        <thead>
            <tr>
                <th>Data</th>
                <th>Temperatura Mínima</th>
                <th>Temperatura Máxima</th>
                <th>Condição</th>
                <th>Chuva (%)</th>
            </tr>
        </thead>
        <tbody>
            {% for dia in previsao %}
            <tr>
                <td>{{ dia.data }}</td>
                <td>{{ dia.temperatura_min }} °C</td>
                <td>{{ dia.temperatura_max }} °C</td>
                <td>{{ dia.condicao }}</td>
                <td>{{ dia.probabilidade_chuva }} %</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>{{ erro }}</p>
    {% endif %}
</body>
</html>